//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntershipManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edit_Log
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<long> Code { get; set; }
        public string Id_User { get; set; }
    }
}
