//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntershipManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internship
    {
        public int Id { get; set; }
        public string TeacherId { get; set; }
        public string StudentId { get; set; }
        public Nullable<int> MajorId { get; set; }
        public Nullable<int> IsConfirm { get; set; }
        public string Confirmby { get; set; }
        public Nullable<int> Status { get; set; }
        public string Createby { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Editby { get; set; }
        public Nullable<System.DateTime> Editdate { get; set; }
        public string Code { get; set; }
        public Nullable<int> EnterpriseId { get; set; }
        public Nullable<int> JobId { get; set; }
        public string StudentName { get; set; }
        public string TeacherName { get; set; }
        public string MajorName { get; set; }
        public string EnterpriseName { get; set; }
        public string JobName { get; set; }
        public string StudentCode { get; set; }
    }
}
