//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntershipManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Slot { get; set; }
        public Nullable<int> EnterpriseId { get; set; }
        public string Createby { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Editby { get; set; }
        public Nullable<System.DateTime> Editdate { get; set; }
        public Nullable<int> MajorId { get; set; }
    }
}
