//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntershipManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string StudentId { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public string Status { get; set; }
        public string TeacherComments { get; set; }
        public Nullable<decimal> Grade { get; set; }
        public Nullable<int> SubmissionRound { get; set; }
        public string Description { get; set; }
        public string FilePath { get; set; }
        public string TeacherId { get; set; }
        public Nullable<int> IsCompleted { get; set; }
    }
}
