//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntershipManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTemplate
    {
        public int Id { get; set; }
        public string TeacherId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> Round { get; set; }
    }
}
