//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntershipManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentClass
    {
        public int Id { get; set; }
        public string StudentId { get; set; }
        public int ClassId { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CourseClass CourseClass { get; set; }
    }
}
